---
name: Checks
on:
  push

env:
  USERNAME: ${{ secrets.DOCKERHUB_USER }}
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Credentials Check
        run: |
          echo "Username: ${{ env.USERNAME }}/${{ env.PASSWORD }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"